version: '2.1'

services:
  idam-authentication-web:
    image: docker.artifactory.reform.hmcts.net/auth/authentication-web:latest
    environment:
    - IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS=false
    - IDAM_ENABLE_PROXY=true
    - IDAM_API_URL=http://idam-api:8080
    links:
    - idam-api
    - service-auth-provider-app
    ports:
    - "3501:8000"

  idam-registration-web:
    image: docker.artifactory.reform.hmcts.net/auth/registration-web:latest
    environment:
    - IDAM_API_URL=http://idam-api:8080
    - IDAM_LOGIN_URL=http://idam-api:8080/login
    - IDAM_REGISTRATION_URL=http://idam-api:8080/register
    - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_REGISTRATION_WEB=AAAAAAAAAAAAAAAA
    links:
    - idam-api
    - service-auth-provider-app
    ports:
    - "3502:8000"

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:latest
    command: --wait-for-database 60
    environment:
    - IDAM_SUPERUSER_EMAIL
    - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
    - SPRING_PROFILES_ACTIVE=test
    - IDAM_TESTING_SUPPORT_ENABLED=true
    - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
    - IDAM_AUTHENTICATION_WEB_HOST=https://idam-authentication-web:8000
    - IDAM_REGISTRATION_WEB_HOST=https://idam-registration-web:8000
    - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_REGISTRATION_WEB=AAAAAAAAAAAAAAAA
    - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_WEBSHOW=AAAAAAAAAAAAAAAA
    - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_GATEWAY=AAAAAAAAAAAAAAAA
    - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_ADMIN=AAAAAAAAAAAAAAAA
    - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_JUIWEBAPP=AAAAAAAAAAAAAAAA
    - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CET_ONLINEAPP=AAAAAAAAAAAAAAAA
    - http_proxy
    - https_proxy
    - no_proxy
    #      logging env vars
    - ROOT_APPENDER=JSON_CONSOLE
    - JSON_CONSOLE_PRETTY_PRINT=false
    - REFORM_SERVICE_TYPE=java
    - REFORM_SERVICE_NAME=idam-api
    - REFORM_TEAM=cc
    - REFORM_ENVIRONMENT=docker
    #      healthcheck env vars
    - PACKAGES_ENVIRONMENT=docker
    - PACKAGES_PROJECT=idam
    - PACKAGES_NAME=idam
    - PACKAGES_VERSION=unkown
    links:
    - smtp-server
    - idam-database
    depends_on:
    - idam-database
    - smtp-server
    ports:
    - "4501:8080"

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database:latest
    ports:
    - "5501:5432"

  smtp-server:
    image: mailhog/mailhog

  service-auth-provider-app:
    image: hmcts/service-auth-provider-app:latest
    environment:
    - MICROSERVICE_KEYS_JUI_WEBAPP=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_EM_GW=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_CCD_DATA=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_CCD_GW=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_CCD_DEFINITION=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_CET_ONLINEAPP=AAAAAAAAAAAAAAAA
    #      logging env vars
    - ROOT_APPENDER=JSON_CONSOLE
    - JSON_CONSOLE_PRETTY_PRINT=false
    - REFORM_SERVICE_TYPE=java
    - REFORM_SERVICE_NAME=service-auth-provider-app
    - REFORM_TEAM=rpe
    - REFORM_ENVIRONMENT=docker
    #      healthcheck env vars
    - PACKAGES_ENVIRONMENT=docker
    - PACKAGES_PROJECT=rpe
    - PACKAGES_NAME=service-auth-provider-app
    - PACKAGES_VERSION=unkown
    ports:
    - "4502:8489"

  cet-onlineapp:
    build:
      context: .
#    image: hmcts/cet-onlineapp:latest
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cet-db:5432/cet
      - SPRING_DATASOURCE_USERNAME=cet
      - SPRING_DATASOURCE_PASSWORD=cet
      - IDAM_API_URL=http://idam-api:8080
      - S2S_URL=http://service-auth-provider-app:8489
      - APPINSIGHTS_INSTRUMENTATIONKEY=test_app
    # these environment variables are used by java-logging library
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=cet-onlineapp
      - REFORM_TEAM=cet
      - REFORM_ENVIRONMENT=docker
    links:
     - cet-db
    depends_on:
     - cet-db
    ports:
    - $SERVER_PORT:8080
    - "7005:7005"

  cet-db:
    image: postgres
    environment:
     - POSTGRES_USER=cet
     - POSTGRES_PASSWORD=cet
     - POSTGRES_DB=cet

    ports:
     - "5432:5432"

  fees-api:
    image: docker.artifactory.reform.hmcts.net/fees-register/fees-api:${FEES_API_DOCKER_VERSION:-latest}
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://fees-database:5432/fees_register
    - SPRING_DATASOURCE_USERNAME=fees_register
    - SPRING_DATASOURCE_PASSWORD=fees_register
    - SPRING_PROFILES_ACTIVE=embedded
    #- AUTH_IDAM_CLIENT_BASEURL=http://idam-api:8080
    - ROOT_APPENDER=JSON_CONSOLE
    ports:
    - 4411:8080
    links:
    #- idam-api
    - fees-database
    depends_on:
    #- idam-api
    - fees-database

  fees-database:
    image: docker.artifactory.reform.hmcts.net/fees-register/fees-database:${FEES_DATABASE_DOCKER_VERSION:-latest}
    environment:
    - FEES_REGISTER_DB_USERNAME=fees_register
    - FEES_REGISTER_DB_PASSWORD=fees_register

  pdf-service-api:
    image: docker.artifactory.reform.hmcts.net/reform/pdf-service-api
    environment:
    - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
    - S2S_URL=http://service-auth-provider-api:8080
    - ROOT_APPENDER
    - JSON_CONSOLE_PRETTY_PRINT
    - ROOT_LOGGING_LEVEL
    - REFORM_SERVICE_NAME=pdf-service
    - REFORM_TEAM
    - REFORM_ENVIRONMENT
    ports:
    - 5500:5500
    healthcheck:
      retries: 40
